% plot_ts_vs_snowpackmeans.m
%
% Plots soil and air temp from recent daily sensor data vs 30-year mean SWE
% , snow depth, and elevation for SNOTEL sites (and subsets of SNOTELS)
%
% Uses daily sensor data in the rawdata/SNOTEL data/ directory and a long-
% term average dataset generated by Greg using 30-year means from NRCS
%
% Note that these soil and air T means aggregate data from all years in 
% daily data files. For plots where years are independent datapoints see
% plot_ts_vs_snowpack.m
%
% Version 2: 111116
%

clear;          % clear memory
close all;      % clear any figures
fignum=0;       % used to increment figure number for plots
%addpath('../m/');
addpath('/home/greg/data/programming/m_common/'); % access to nanmean, etc

% Set data path and file name, read in file
datapath = '../datafiles/';

% Load list of sites with data in the daily data directory
havedata = unique(dlmread([datapath 'allsensors_daily/_sitelist.txt']));

% Generate list site 30yr average data from 7100_avgprecipswe file
% Create format string (state, siteID, siteName, elev, P_tot, Max_swe)
formatstr = '%s%f%s%f%f%f';
fid = fopen([datapath 'longterm_averages/'...
    '7100_avgprecipswe_ALLsnotel.csv']);
listcell = textscan(fid, formatstr,'Headerlines', 1, 'Delimiter', ',');
fclose(fid);

% Put cells containing siteID, elev, P_tot, and Max_SWE together
sitesarray = [listcell{2}, listcell{4}, listcell{5}, listcell{6}];
clear listcell;

% Filter out sites for which there is no data in the data folder
havedatatest = ismember(sitesarray(:,1), havedata);
sitesarray = sitesarray(havedatatest, :);

% Import list of wasatch + uinta sites
formatstr = '%s%f%s%s';
fid = fopen([datapath 'wasatchuintasites.csv']);
wasatchuintacell = textscan(fid, formatstr,'Headerlines', 1, 'Delimiter', ',');
fclose(fid);

% Creat list of wasatch and uinta sites
test = strcmpi(wasatchuintacell{4}, 'WASATCH') | ...
    strcmpi(wasatchuintacell{4},'UINTAH');
wasatchuintas = wasatchuintacell{2}(test);
clear test;

% Create a test to plot a subset of sites in sitesarray (wasatch and uintas)
wasatchuintatest = ismember(sitesarray(:,1), wasatchuintas);

% Remove bad sites
badsitetest = ismember(sitesarray(:,1), [583, 935, 358, 1042]);
sitesarray(badsitetest, :) = [];

% Load data for each site into a large cellarray
for i = 1:length(sitesarray);
    [m, ~] = loadsnotel('daily', sitesarray(i,1));
    dailysite_datevec = datevec(m{2}, 'yyyy-mm-dd');
    % Create logical test for July and February
    julytest = dailysite_datevec(:,2)==7;
    februarytest = dailysite_datevec(:,2)==2;
    decembertest = dailysite_datevec(:,2)==12;
    % Append calculated values on to sitesarray
    % All of these (below) are calculated from the daily datasets
    sitesarray(i, 5) = nanmean(m{7}(julytest));% July mean max air temp
    sitesarray(i, 6) = nanmean(m{9}(julytest));% july mean avg air temp
    sitesarray(i, 7) = nanmean(m{14}(julytest));% july mean 5cm soil temp
    sitesarray(i, 8) = nanmean(m{7}(februarytest));% feb mean max air temp
    sitesarray(i, 9) = nanmean(m{9}(februarytest));% feb mean avg air temp
    sitesarray(i, 10) = nanmean(m{14}(februarytest));% feb mean 5cm soil temp
    sitesarray(i, 11) = nanmean(m{4}(februarytest));% feb mean SWE
    sitesarray(i, 12) = nanmean(m{10}(februarytest));% feb mean snow depth
    sitesarray(i, 13) = nanmean(m{4}(decembertest));% dec mean SWE
    sitesarray(i, 14) = nanmean(m{10}(decembertest));% dec mean snow depth
    sitesarray(i, 15) = nanmean(m{9}); % Mean annual air temp 
    sitesarray(i, 16) = nanmean(m{14}); % Mean annual 5cm soil temp
    % test if there is an average ?
end

% PLOTS
%
% Mean annual air and soil temps vs elevation and SWE
fignum = fignum+1;    
h = figure(fignum);
set(h, 'Name','% Mean Feb soil temp by SWE & snow depth, SNOTEL sites');
% Mean annual air temp vs elevation
subplot 221;
plot(sitesarray(:,2), sitesarray(:,15), 'ok');
xlabel('Elevation (m)');
ylabel('Mean annual air temp (Celsius)');
title('MAT vs elevation');

% Mean annual air temp vs 30yr SWE
subplot 222;
plot(sitesarray(:,4), sitesarray(:,15), 'ob');
xlabel('30yr SWE');
%ylabel('Mean annual air temp (20cm)');
title('MAT vs SWE');

% Mean annual soil temp vs elevation
subplot 223;
plot(sitesarray(:,2), sitesarray(:,16), 'or');
xlabel('Elevation (m)');
ylabel('Mean annual soil temp (Celsius)');
title('Mean soil temp vs elevation');

% Mean annual soil temp vs 30yr SWE
subplot 224;
plot(sitesarray(:,4), sitesarray(:,16), 'om');
xlabel('30yr SWE');
%ylabel('Mean annual soil temp (20cm)');
title('Mean soil temp vs SWE');


% Feb soil temps vs snowpack in Feb and Dec (aggregated)
% The december test checks if soil temp is dependent on antecedent snowpack
% Note that each datapoint integrates ALL years, not individual years of
% data
fignum = fignum+1;    
h = figure(fignum);
set(h, 'Name','% Mean Feb soil temp vs Feb and Dec snowpack (aggregated data)');
% Mean Feb soil temp by SWE
subplot 221;
plot(sitesarray(:,11), sitesarray(:,10), 'ok');
xlabel('Mean Feb SWE');
ylabel('Mean Feb soil temp (Celsius)');
title('Feb soil temp vs Feb SWE');

% Mean Feb soil temp by snow depth
subplot 222;
plot(sitesarray(:,12), sitesarray(:,10), 'ok');
xlabel('Mean Feb snow depth');
%ylabel('Mean Feb soil temp (Celsius)');
title('vs Feb snow depth');

% Mean Feb soil temp by December SWE
subplot 223;
plot(sitesarray(:,13), sitesarray(:,10), 'ob');
xlabel('Mean Dec SWE');
ylabel('Mean Feb soil temp (Celsius)');
title('vs Dec SWE');

% Mean Feb soil temp by Dec snow depth
subplot 224;
plot(sitesarray(:,14), sitesarray(:,10), 'ob');
xlabel('Mean Dec snow depth');
%ylabel('Mean Feb soil temp (Celsius)');
title('vs Dec snow depth');


% July soil and air T vs elevation and SWE
fignum = fignum+1;    
h = figure(fignum);
set(h, 'Name','July and Feb temps vs elevation');
% Mean July temps vs elevation
subplot 221;
plot(sitesarray(:,2), sitesarray(:,7), 'ok');
hold on
plot(sitesarray(:,2), sitesarray(:,6), 'ob');
xlabel('Elevation (m)');
ylabel('Mean July T');
legend('Soil T (20cm)', 'Air T');
title('July temps vs Elevation');

%Mean Feb temps vs elevation
subplot 222;
plot(sitesarray(:,2), sitesarray(:, 10), 'ok');
hold on
plot(sitesarray(:,2), sitesarray(:, 9), 'ob');
xlabel('Elevation (m)');
ylabel('Mean Feb T');
legend('Soil T (20cm)', 'Air T');
title('Feb temps vs Elevation');

% Mean July soil temps vs air temps
subplot 223;
plot(sitesarray(:,6), sitesarray(:, 7), 'ok');
xlabel('Mean July AirT');
ylabel('Mean July SoilT');
title('July soil vs air temp');

% Mean Feb soil temps vs air temps
subplot 224;
plot(sitesarray(:,9), sitesarray(:, 10), 'ok');
xlabel('Mean Feb AirT');
ylabel('Mean Feb SoilT');
title('Feb soil vs air temp');


% Mean July Soil Temperature vs 30 yr Peak SWE
fignum = fignum+1;    
h = figure(fignum);
set(h, 'Name','Mean July Temps vs 30yr Peak SWE');

%select and add data to niwot ridge
niwottest = sitesarray(:,1) == 663;
sitesarray(niwottest, 7) = 10.05;

subplot 221;
plot(sitesarray(:,4), sitesarray(:,7), 'ob');
hold on
plot(sitesarray(wasatchuintatest,4), sitesarray(wasatchuintatest,7), 'ob', 'MarkerFaceColor', 'b');
plot(sitesarray(niwottest,4), sitesarray(niwottest, 7), 'pk', 'MarkerFaceColor', 'w', 'MarkerSize', 12);
ylabel('Mean July soil T (Celsius)');
xlabel('Mean Peak SWE (mm)');
ylim([5, 25]);
legend('CO, UT, ID, WY SNOTEL sites', 'Wasatch and Uinta SNOTEL sites', 'Niwot Ridge SNOTEL');

subplot 222;
plot(sitesarray(:,4), sitesarray(:,6), 'ob');
hold on
plot(sitesarray(wasatchuintatest,4), sitesarray(wasatchuintatest,6), 'ob', 'MarkerFaceColor', 'b');
plot(sitesarray(niwottest,4), sitesarray(niwottest, 6), 'pk', 'MarkerFaceColor', 'w', 'MarkerSize', 12);
ylabel('Mean July air T (Celsius)');
xlabel('Mean Peak SWE (mm)');
ylim([5, 25]);


junk = 99;
